### ISSUE TITLE
The Playback Rewrite

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#1057]
# :rocket: The Playback Rewrite

We've often talked about the "playback rewrite" but there was no issue tracking it's progress. I'm not promising this issue to be up-to-date all the time but I'll use it myself to track progress on the rewrite.

The goal is to rewrite all playback related code: video playback, audio playback and live tv. The new code should be easier to maintain and be prepared for a migration to Jellyfin 11. New features like SyncPlay can be added without much trouble. All code is Kotlin-first and uses the new SDK.

We've mentioned the playback rewrite to be in a 0.13 release but we've since changed our release schedule and it will not be included in 0.13 anymore. We're not giving any ETA for when it will happen.

## :game_die: Process

The initial proof-of-concept will be written on a separate branch (on my fork) until the preparations are ready. At that point it will be PR'd to the master branch in a separate Gradle module. To use it a flag (in the build file?) needs to be set. This way we can release new versions of the app while developing the new playback code on the master branch. To support a rapid development cycle PR's that are not reviewed after 5 days may be self-merged if they only touch the playback module (changes to everything outside requires a review).

Issues and pull requests related to the new playback code will be added to the "playback rewrite" project on GitHub. The "playback" label will not be used until the playback rewrite is released to the public.

## :trophy: Milestones

This list will change, some features might not be available on initial release. When possible issues/pull requests will be linked for tracking purposes. There is no particular order for this list, new features might be added before restoring older features.

### :building_construction: Preparations

Various tasks that need to be completed to work on the rewrite.

- [x] Create new Kotlin-first SDK
- [x] Add new SDK
- [ ] Support multiple Gradle modules when building

### :fireworks: Proof of Concept

- [ ] Add playlist support - everything is a playlist, even single item playback
- [ ] Add bare-bones player UI
- [x] Add ExoPlayer backend
- [ ] Load video from server
- [ ] Report playback progress to server

### :arrows_counterclockwise: Restoring features

- [ ] Support transcoding/remuxing
- [ ] Add LibVLC backend
- [ ] Add remote control API
- [ ] Add intros
- [ ] Add chapter support
- [ ] Move "next up" screen to new playback code

### :hammer_and_wrench: Integration

- [ ] Use new playback module for audio (music, podcasts, audiobooks etc.)
- [ ] Use new playback module for video (movies, series etc.)
- [ ] Use new playback module for Live TV
- [ ] Delete old playback code

### :boom: Adding new features

- [ ] Add smart codec detection for directplay, remux and transcoding
- [ ] Add system preferences to overwrite codec support manually
- [ ] Add Media Session integration
- [ ] Add SyncPlay
- [ ] Add MPV backend

## :exclamation: This issue

Please do not reply to this issue for any questions about the playback rewrite. The comment sections is meant for our contributors to give updates or discuss the implementation. For anything else, please create a new issue or discussion. We may delete your comment if we consider it off topic.

**Comment by mueslimak3r** [comment]
I was looking intro the code for trailer playback last night and I see that the object for external trailers just uses links videos (eg: a link to a youtube video). I'm not sure how feasible it would be, but it seems like a good design for a re-written player might be for it to just play video links. Then other classes would be queried for stuff specific to jellyfin like subtitle object classes, mediastream info, etc.

With the current player it's entirely designed around using jellyfin specific classes like BaseItemDto and its MediaStreams and SubtitleInfos, etc. Because of this it's not possible to make exoplayer play an arbitrary youtube link, even though exoplayer is capable of doing so.

**Comment by nielsvanvelzen** [comment]
> it seems like a good design for a re-written player might be for it to just play video links.

The current implementation already does this, it never uses the Jellyfin API directly to make it easier to update if the ever API changes. This doesn't mean that YouTube video is supported though, the implementation will only allow video from the Jellyfin server. If we want to support YT a server plugin should deal with that, not the client.

> Then other classes would be queried for stuff specific to jellyfin like subtitle object classes, mediastream info, etc.

My idea is to create some kind of "lookup" service where the playback code queries for data. This service would be implemented in the app code. I haven't worked on this part yet.

> it's not possible to make exoplayer play an arbitrary youtube link, even though exoplayer is capable of doing so.

I don't think this is possible without using the proprietary YouTube API.

**Comment by Andy2244** [comment]
Just a quick note regarding your thoughts on "Rethink external player support".

The most interesting players that have better or more features than Exoplayer nearly all have a basic API, so its mainly a matter of implementing the available api. So my suggestion would be to define a clear interface that can be implemented for a particular player. So as example there is often no need to use a external player for audio, while you do want to use it for video. So having a interface to probe what is implemented and whats not may help.

Just a suggestion.

**Comment by nielsvanvelzen** [comment]
Quick update for everyone watching the progress on this rewrite. I'm still working on it! Even though the issue was made quite a while ago I've made a lot of progress but also started over a few times. I want to get the basics right so we don't end up with unmaintainable code.

My focus is currently on getting audio-only media to work perfect before proceeding with video support. This will probably mean that eventually the app releases an update with the new playback code for music/audiobooks and the old playback code for series/movies.

The following list of features are working locally already, there might even be more I forgot to mention:
- Queueing with lazy loading
- Media session support (the notification on the home screen for what media is playing, this also allows controlling via the google assistant / smartwatches etc.)
- Jellyfin remote control
- Jellyfin Playstate (showing what is playing in the dashboard, marking items as watched/listened etc.)
- Basic audio playback (no transcoding)
- Gappless playback

There's still a lot of bugs and some design decisions to make in the overall architecture. Hopefully this it won't be too long before the first pull requests with actual code go up. Thanks everyone for waiting!

**Comment by gitdeath** [comment]
Would the Media Session Support mentioned be the solution for #441?

**Comment by nielsvanvelzen** [comment]
Yes media session support will fix $441 and no they're not easy to integrate in the existing playback code. If everything goes right the rewritten playback code will be available in 0.16 for music playback (no promises).

**Comment by nielsvanvelzen** [comment]
I've updated the initial post; removed some unnecessary info. Rewritten the intro and added a list of changes required in the server.

The past few weeks saw quite some progress on the rewrite (see the linked PR's above this comment). The current plan is to use the new playback code for audio playback (music/audiobooks) first before working on video again. This is mainly because it's easier to get the architecture started and have some working code.

Music playback is already working for me locally and I'm slowly cleaning all code and making pull requests to get it into the main repository.

Thanks for being patient with my 2 year rewrite project 😄

**Comment by GGProGaming** [comment]
Yeesh. 2 years ago and 12 have been finished

**Comment by nielsvanvelzen** [comment]
Hello everyone, I'm back with another status update!

The last few weeks saw a bunch of changes (see pull requests above this comment) and I can now say: **we have reached feature parity with the old music player** 🎉. Today I merged a change that uses the new playback code as default for music (and other stuff using the audio player).

Work will continue to add additional features, improve performance and fixing bugs. I will also accept pull requests to the new playback code now. Please discuss first with me if you're planning to make changes.

When 0.16 is released I will start work on video playback so we can hopefully fully replace the existing player code in 0.17/0.18 (as always; no promises). I plan to start the beta cycle for 0.16 in the coming months.

_PS: a quick reminder to read the issue description before replying, your comment is likely to be removed/hidden. Also read our [Code of Conduct](https://jellyfin.org/docs/general/community-standards#code-of-conduct) before complaining to unpaid volunteers._

**Comment by nielsvanvelzen** [comment]
### **[The first beta for 0.16 is here!](https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.16.0-beta.1).**

As said in previous posts, this release uses the rewritten playback code for all music playback by default. Like all beta releases it will be available in the beta program on Google Play only when it's been trough review.

If you encounter any issues you can (temporarily) switch back to the old backend from the app preferences, please report your findings on GitHub (in a new issue) so I can fix the bugs before release.

I'm already working on the initial changes for video support locally which I'm hoping to make a part of 0.17 (no promises!) which I'm hoping to release before the end of this year (also no promises!).

_If you appreciate my work, you can support me by [donating via GitHub sponsors](https://github.com/sponsors/nielsvanvelzen). I use this money to buy equipment my development machine and for hardware to test specific issues, right now I'm looking into upgrading my audio gear (currently using built-in stereo speakers on my television) to help with various audio issues._

**Comment by thor2002ro** [comment]
even if av1 still doesnt work in the client on amazon fire tv 4k max that has av1 this check "Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q" in jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt will fail since the stick reports android 9

**Comment by Yeetov** [comment]
Is this the same code for the fire stick (firetv) or just android TV?

**Comment by nielsvanvelzen** [comment]
Let me give all of you another (quick) status update about the famous playback rewrite. I've been very busy the past few weeks (might even be months, didn't check) on a few key points:

1. 10.9 compatibility. This work happens in multiple places, from manually validating each API change in the release to updating the SDK and updating the app. This work is now done and the current 0.16.z releases of the app are fully compatible.
2. Refactoring the app to fully use the SDK. I recreated the layer that talks with the API a few years back, this is our "Kotlin SDK". However, the app still used our old "Java Apiclient" in most places. With all new additions in 10.7, 10.8 and 10.9 I could no longer not use the SDK as all newly added features could not be used. This migration took up most of my time and I can now say that almost all code is using the SDK! The first (real) 10.9 feature I added is support for normalization gain in music playback (#3660)!
3. Rethinking some core components of the playback code. Most of this is now implemented and this should make it easier to add video playback related functionality.
4. Add video support. The initial changes are already merged, and development builds have an option to enable it. It's highly experimental but it does work, you can play video now.

While all of this is great news, I'm also working towards the next release of the app, 0.17.0. The current release started its beta cycle almost a year ago so it's time for a new one. Considering the new video playback is still very early it will not be ready for 0.17. The experimental option for it will also most likely be hidden for the release (still debating this part).

This was the quick status update for now, I didn't bother too much with the formatting or even re-reading it so forgive me for any mistakes. Hoping to give the next status update a lot quicker!


Happy watching!


_If you appreciate my work, you can show your support with a [donation through GitHub sponsors](https://github.com/sponsors/nielsvanvelzen)._

**Comment by MulverineX** [comment]
I'm starting to wonder whether this is ever going to materialize for video playback? I may be looking at the state of the project at the wrong angle, but it seems like everything *but* work on the most common use case for this app is being worked on. I understand the perils of motivation & drive, especially when not being in a traditional work environment, but I would really like to see some sort of progress here. As it stands, there is still no actually good, competitive solution for watching video content from Jellyfin on Android TV. Every current solution has major issues that you are forced to work around, and the only use case that actually seems to be stable is where all content is stored in ridiculously low, ancient compression (h264) or where the Jellyfin server has ridiculously high hardware allocation where all content is transcoded.

Edit: Wholphin exists now

**Comment by NickM-27** [comment]
Not being involved with the project but as a developer, if I had to guess the audio / other cases likely involve a lot of shared logic with video and is easier to work on, hence it gets worked on first.

> and the only use case that actually seems to be stable is where all content is stored in ridiculously low, ancient compression (h264) or where the Jellyfin server has ridiculously high hardware allocation where all content is transcoded.

I understand there are a lot of things to consider, but this is definitely not my experience. Jellyfin as it is now on Android TV is already entirely stable on my Nvidia Shield, watching anything from Dolby Vision / Dolby Atmos Star Wars to basic HEVC / stereo movies. Nothing is every transcoded in my case.
