### ISSUE TITLE
Login Redesign

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#612]
A lot of progress has been made now and the original list is now mostly finished, with some features being dropped or considered for later releases. A new list of smaller tasks related to the login UI below:

- [ ] After adding a new server the server list screens become out of sync - issue in viewpager1 needs migration
- [ ] Error reporting in the add server dialog could be more detailed, For example SSL errors happen often with our users but right now it shows the name of the SSL error exception..
- [ ] Error reporting in the add user dialog could be more detailed
- [x] "logout" should be renamed to "switch user" or something similar - #816
- [x] Normalize server address input so the user can forget to add a protocol etc. - #818
- [x] Removing a server from the server management screen doesn't update the server management screen - #815

Those are not for the login redesign but I needed to put it somewhere - @nielsvanvelzen
- [ ] Remove unused strings (avoid conflict with weblate please)

__Original below__
------

**Describe the feature you'd like**

The login workflow is being completely reimplemented. The initial work for this was handled in #578, but the following items need addressed as follow up tasks:

* Saving servers and previously logged in users (current implementation only saves most recent login)
  * [x] Saving previously logged in users and servers
  * [x] Add new server without restart  #730 
  * [x] After restarting the app my user (that I just signed in) is gone and I'm not automatically authenticated
* [x] Finish ui/ux of server listing screen
    * Currently relies on existing `GridButton` implementation
    * "Add Server" button is using default styling and may need some tweaking
    * [x] User avatars are not displayed #701
    * Round buttons?
    * ~~Go directly to add server screen if no servers are found~~
    - [x] The login screen when no server is added should show something like "no servers here yet" or maybe even show a "welcome" screen for new users. (https://f.ndat.nl/1604672131.png) #730
* [x] Finish ui/ux of add server screen
    - [x] The "enter server address" screen should submit the url when pressing the OK/ENTER button on a remote to avoid dpad navigation to the "OK" button #727
* [x] Finish ui/ux of login screen
    * Should we display user avatars when possible?
    - [x] Pressing OK/ENTER should signin instead of focussing on the OK button #726
* [ ] PIN support
* [ ] Quick connect support
* [x] Managing saved servers and users (option to remove/forget) #713 
* [ ] Support re-ordering servers?
* [ ] Use kotlinx.serialization instead of gson
* [ ] Add error messaging for invalid server or user credentials
    * After adding my own server the app returned to the login screen but nothing happened and my server was not added. I later found out this was due too an untrusted certificate. These kinds of errors should be handled
* [ ] Use androidx.navigation

**Related issues:**
#167 
#223 
#528 
#536

**Comment by Nickbert7** [comment]
Can we please also get a "remember me" checkbox?
So I don't have to go to the settings to keep me signed in.

**Comment by nielsvanvelzen** [comment]
I'm working on saving the servers/users using a local JSON based store and the Android AccountManager.

![image](https://user-images.githubusercontent.com/2305178/99824086-7c25d200-2b55-11eb-8219-548d7ebd97d5.png)  
This diagram illustrates the data sources that will be used in the end to show servers/users

The JSON schema currently looks like this:
```json
{
	"version": 1,
	"servers": {
		"UUID": {
			"name": "",
			"url": "",
			"last_used": "2020-11-20T16:13:00+02:00",
			"display_order": 1,
			"users": {
				"UUID": {
					"name": "",
					"profile_picture": "",
					"last_used": "2020-11-20T16:13:00+02:00",
					"display_order": 1
				},
				"UUID": { ... }
			}
		},
		"UUID": { ... }
	}
}
```

I've added a version number in the case we ever need to make changes to the document.

The AccountManager will store the access_token and on app start the local credential document will be synced with the AccountManager.

**Comment by MrChip53** [comment]
> * [ ]  Saving servers and previously logged in users (current implementation only saves most recent login)
>   
>   * After restarting the app my user (that I just signed in) is gone and I'm not automatically authenticated

Can be broken up now.

- [x] Saving previously logged in users and servers
- [ ] Add new server without restart

**Comment by nielsvanvelzen** [comment]
The key feature missing right now is auto-login. I'll pick that up this weekend. With that included I think 0.12 should be feature-ready and we can start focusing on details like better error reporting for connection issues and such. We might want to split this issue into multiple at that point (the starting-post is slightly outdated already).

**Comment by MrChip53** [comment]
Would #730 be enough to consider re-ordering servers checked?

**Comment by nielsvanvelzen** [comment]
Yes and no, it re-orders automatically now. Not sure if we want manual sorting.

**Comment by nielsvanvelzen** [comment]
Updated the issue to a new todo list with tasks for release. Please add more (or comment) when you find anything.

**Comment by viggy96** [comment]
I believe PIN support is already there. At least I've been using my PIN to login without any issues.

**Comment by whalehub** [comment]
@nielsvanvelzen Was support for the Quick Connect feature also added in the #944 rewrite?

**Comment by nielsvanvelzen** [comment]
No, the current implementation of Quick Connect in the server did not allow us to properly add it to the app. I've made changes so we can implement it with server version 10.8.

Related pull requests for that:

- jellyfin/jellyfin#6200
- jellyfin/jellyfin-web#2747
- jellyfin/jellyfin-web#2748
- jellyfin/jellyfin-web#2749
